### PR TITLE
[Sedona-68] Add St_Collect function.

### PR DESCRIPTION
**Pull request by Imbruced**
## Is this PR related to a proposed Issue?

[SEDONA-68](https://issues.apache.org/jira/browse/SEDONA-68)

## What changes were proposed in this PR?
ST_Collect function

## How was this patch tested?
Scala, Python integration tests

## Did this PR include necessary documentation updates?
Yes

### CODE REVIEW

**Review by jiayuasu — COMMENTED** [review]
@Imbruced Looks like your IDE refactor all formats in Functions.scala, is this necessary?

**Comment by Imbruced** [comment]
@jiayuasu sorry for that, I had some style violation inside tests to fix that I installed scala style and by accident functions file was also "fixed".

**Comment by Imbruced** [comment]
@jiayuasu What is our approach to solved issues on Jira ? Can I close them ? Examples, support for spark 3.2, ST_SetSRID etc.

**Comment by jiayuasu** [comment]
@Imbruced You can leave those JIRA tickets open but add fixed version in it. Once the version is release, you or I can close those tickets.

I will leave this PR to the next release because 1.1.1-incubating is now in the voting phase.

**Review by jiayuasu — APPROVED** [review]

**Pull request merged**
