### PR TITLE
[DOCS] Fix the R test that still has DBI call

### PR DESCRIPTION
**Pull request by jiayuasu**
## Did you read the Contributor Guide?

- Yes, I have read [Contributor Rules](https://sedona.apache.org/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/community/develop/)

## Is this PR related to a JIRA ticket?

- No, this is a documentation update. The PR name follows the format `[DOCS] my subject`.

## Did this PR include necessary documentation updates?

- No, this PR does not affect any public API so no need to change the docs.

### CODE REVIEW

**Comment by jiayuasu** [comment]
@yitao-li Dear Yitao, could you please help me remove the DBI call in the test? My PR didn't work for this...

**Review by yitao-li — APPROVED** [review]
Nice catch!

**Comment by yitao-li** [comment]
Uh just noticed the build failures... ok I'll take a look soon

**Review by yitao-li — CHANGES_REQUESTED** [review]
need to fix test failure (should be simple, I think) -- looking into it now

**Comment by yitao-li** [comment]
@jiayuasu I think https://github.com/apache/incubator-sedona/pull/731 should fix it.
The CI run for that PR was cancelled after some unrelated test failure though, but if I run my version of `sdf_sql(...) %>% collect()` locally, I do get the expected result, so, I think it should work.

**Pull request closed without merging**
