### PR TITLE
[SEDONA-31] Rename sparklyr.sedona to apache.sedona

### PR DESCRIPTION
**Pull request by jiayuasu**
## Is this PR related to a proposed Issue?

https://issues.apache.org/jira/browse/SEDONA-31

## What changes were proposed in this PR?

A follow-up PR for Sedona R. This is to change the package name from `sparklyr.sedona` to `apache.sedona` in order to be compliant to Apache Software Foundation requirement

## How was this patch tested?

Pass CI tests

## Did this PR include necessary documentation updates?

Docs in R vignette are ready but steps to generate the R docs are not documented.

### CODE REVIEW

**Comment by jiayuasu** [comment]
@yitao-li 

Hi Yitao, I am preparing the next release of Sedona. In order to be compliant with ASF requirement, I have to rename this module to `apache.sedona`. Do you have any concern regarding this PR?

**Comment by yitao-li** [comment]
@jiayuasu Hey the change looks fine :+1:

To re-generate roxygen docs and everything else, run the following

```
cd R  # i.e., the current root directory of this R package after this change
Rscript -e 'install.packages("roxygen2")' # if you haven't installed the {roxygen2} package already
Rscript -e 'roxygen2::roxygenize()'
# and then sanity-check and commit the generated changes
```

**Comment by jiayuasu** [comment]
@yitao-li How do you generate the README file in the R folder? I'd like to find an easy way to produce markdown files based on the Rmd tutorials in vignette folder then I can merge these tutorials to https://sedona.apache.org/ which is written in markdown: https://github.com/apache/incubator-sedona/tree/master/docs

**Comment by yitao-li** [comment]
@jiayuasu One way to obtain the .md files is to run `rmarkdown::render("vignettes/<topic>.Rmd", clean = FALSE)` (`clean = FALSE` meaning do not delete intermediate .md files) and then merge the generated <topic>.knit.md file with the rest of the website.

**Pull request merged**
