### PR TITLE
[DOCS] Create python-vector-osm.md

### PR DESCRIPTION
**Pull request by carolgit**
I've found it difficult to find more complex examples at this documentation so I made this one, that involves spark slaves, osm data and hdfs. I hope it can be helpfull to someone else in the future.

## Is this PR related to a proposed Issue?

No
## What changes were proposed in this PR?
A new documentation example to guide other developers, in a more complex environment, closest to reality of some needs they may have as well

## How was this patch tested?

The examples were tested at jupyter, connected to a spark infrastruture, with 4 slaves machines

## Did this PR include necessary documentation updates?
Yes

### CODE REVIEW

**Comment by jiayuasu** [comment]
@carolgit Thanks for your contribution! I think your tutorial is more suitable for a standalone Jupyter notebook example.

Can you make it a runnable example on binder and add it to our binder examples? https://github.com/apache/incubator-sedona/tree/master/binder

**Comment by netanel246** [comment]
@jiayuasu ,
I can take that if it's OK.

**Comment by jiayuasu** [comment]
@netanel246 Please go ahead :-)

**Comment by jiayuasu** [comment]
@netanel246 I will merge this PR and move the notebook to `binder/contrib`. You can still work on the notebook if you want.

**Pull request merged**
