### PR TITLE
Jtsplus python fix

### PR DESCRIPTION
**Pull request by Imbruced**
## Is this PR related to a proposed Issue?
#484 
## What changes were proposed in this PR?
Fix failing python tests

## How was this patch tested?
-
## Did this PR include necessary documentation updates?
No

### CODE REVIEW

**Comment by Imbruced** [comment]
@jiayuasu That's PR to resolve an issue with Python tests. But one thing worries me. Can we add to POM, definition of fat jar for Python purposes ? Currently to make it work I have to add additional jars, which may not be user friendly and in addition it causes continuous CI script modification when we change dependencies versions.

**Review by jiayuasu — COMMENTED** [review]
Hi @Imbruced ,

1. I notice there are some binary files in the test/resource folder, such as ".part-0000.crc"
Are these binary files necessary to be included?

2. The reason why we remove the geotools dependencies is that the license of these jar is not compatible with Apache Software Foundation. So they cannot be included in the source code and release.

In order to fix it, in out new release, we need to add the list of required GeoTools jars in our document website and ask users to download them.

**Comment by Imbruced** [comment]
@jiayuasu 
1. Files are used by few tests.
2. I can try to create additional jar file which will be published on PyPI with wheel files (consists of those missing dependencies).

**Comment by jiayuasu** [comment]
@Imbruced That sounds good!

Let's do it in a separate PR. The next PR in Sedona will be the name change for all paths, then you can finalize the wheel file there. We will have to generate our first Apache release on Spark 3.0 ASAP. Many users are waiting for it.

**Review by jiayuasu — APPROVED** [review]

**Pull request merged**
