### PR TITLE
[SEDONA-98] Added ST_IsEmpty function

### PR DESCRIPTION
**Pull request by Arindam-Jain**
## Is this PR related to a proposed Issue?
[SEDONA-98](https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-98)
## What changes were proposed in this PR?
Added ST_IsEmpty function to SQL and flink 
## How was this patch tested?
Added unit tests
## Did this PR include necessary documentation updates?
Yes

### CODE REVIEW

**Review by jiayuasu — CHANGES_REQUESTED** [review]
This function is NOT consistent with PostGIS: https://postgis.net/docs/ST_IsEmpty.html

You should use geometry.Is_Empty() function: https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html#isEmpty--

Do NOT use GeomUtils.

**Comment by Arindam-Jain** [comment]
@jiayuasu I have changed GeomUtils to geometry.isEmpty() function. Could you please let me know what else is inconsistent?

**Review by jiayuasu — CHANGES_REQUESTED** [review]
Do NOT commit .DS_Store file

**Comment by Arindam-Jain** [comment]
Y

> Do NOT commit .DS_Store file

Yes will remove it

**Comment by Arindam-Jain** [comment]
> Do NOT commit .DS_Store file

@jiayuasu Can I add it to .gitignore ?

**Comment by jiayuasu** [comment]
> > Do NOT commit .DS_Store file
> 
> @jiayuasu Can I add it to .gitignore ?

Just remove it.

**Comment by Arindam-Jain** [comment]
> > > Do NOT commit .DS_Store file
> > 
> > 
> > @jiayuasu Can I add it to .gitignore ?
> 
> Just remove it.

Okay!

> > > Do NOT commit .DS_Store file
> > 
> > 
> > @jiayuasu Can I add it to .gitignore ?
> 
> Just remove it.

Yes working on it, was waiting for checks to pass

**Comment by Arindam-Jain** [comment]
.DS_Store file removed!

**Review by jiayuasu — APPROVED** [review]

**Comment by jiayuasu** [comment]
Please add the JIRA url of the ticket in the description. Just like what other PRs do.

**Comment by Arindam-Jain** [comment]
> Please add the JIRA url of the ticket in the description. Just like what other PRs do.

Sure, will do!

**Pull request merged**
