### PR TITLE
[SEDONA-3] First release: change path names and file headers

### PR DESCRIPTION
**Pull request by jiayuasu**
## Is this PR related to a proposed Issue?

Prepare the first Sedona release: `1.0.0-incubator `

## What changes were proposed in this PR?

Change all paths to org.apache.sedona

### Scala and Java:

The new path of sub-modules is as follows:

```
Core: org.apache.sedona.core
SQL: org.apache.sedona.sql
VIZ: org.apache.sedona.viz
```
Classpath inside Spark SQL kernal

```
SQL: org.apache.spark.sql.sedona_sql
VIZ: org.apache.spark.sql.sedona_viz
```

All class files which have the name prefix "GeoSpark" have been changed to either the prefix "Sedona" or no prefix

All comments which have "GeoSpark" have been updated to "Sedona" accordingly.

The code has been restructured, re-formatted and cleaned.

### Python

To be done by @Imbruced 

## Did this PR include necessary documentation updates?

Will be handled in a separate PR

### CODE REVIEW

**Comment by Imbruced** [comment]
@jiayuasu I can see that only viz tests are failing, so I started to work on Python version. I should finish soon.

**Comment by Imbruced** [comment]
@jiayuasu Python version is almost there, I need to combine dependencies to one package and fix one test, but I found out that one of geospark core tests failing due to invalid records number. 
```java
Failed tests: 
  CRSTransformationTest.testPolygonDistanceJoinWithCRSTransformation:375 expected:<5467> but was:<5472>
```

**Comment by jiayuasu** [comment]
@Imbruced This is because when I cleaned up the code, somehow messed up the test data files. The error in Viz is also caused by this.

I was very busy in the past week so didn't fix it. But now I get sometime, I will fix it in two or three days. If I cannot fix the test data file, I will redo this PR from scratch. Please stay tuned.

**Comment by jiayuasu** [comment]
@Imbruced I have fixed the failed Viz test cases. But the core test does not fail on my machine: CRSTransformationTest.testPolygonDistanceJoinWithCRSTransformation:375 expected:<5467> but was:<5472>

All test cases in Scala and Java API of core, sql and viz have passed. You can also verify this in the Travis CI build.

You can focus on the Python side

**Comment by netanel246** [comment]
@jiayuasu Hello Jia, hope you are doing well.
Is there anything I can help with?

**Comment by jiayuasu** [comment]
@Imbruced Any updates?

**Comment by Imbruced** [comment]
@jiayuasu I am almost there, today I will create PR.

**Pull request merged**
